=== Zapelo1985/appWeb/alumnos.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellido, edad, residencia, sexo, pais)>
<!ATTLIST alumno id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT residencia (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

=== Zapelo1985/appWeb/ej6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="css/ej6.css"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">
<alumnos>
    <alumno id="1">
        <nombre>David</nombre>
        <apellido>Griñán</apellido>
        <edad>38</edad>
        <residencia>Montequinto</residencia>
        <sexo>Hombre</sexo>
        <pais>España</pais>
    </alumno>
    <alumno id="2">
        <nombre>Manuel Jesús</nombre>
        <apellido>Venegas</apellido>
        <edad>22</edad>
        <residencia></residencia>
        <sexo>Hombre</sexo>
        <pais>España</pais>
    </alumno>
    <alumno id="3">
        <nombre>Alfonso</nombre>
        <apellido>Zambrana</apellido>
        <edad>20</edad>
        <residencia></residencia>
        <sexo>Hombre</sexo>
        <pais>España</pais>
    </alumno>
    <alumno id="4">
        <nombre>Jesús</nombre>
        <apellido>García</apellido>
        <edad>21</edad>
        <residencia></residencia>
        <sexo>Hombre</sexo>
        <pais>España</pais>
    </alumno>
</alumnos>
